---
title: "s2-data-diagnosis"
author: "LetingZhang"
date: "5/1/2021"
output: html_document
---

```{r}
library(ggplot2)
```



```{r Load data}
load("~/Covid-Cyber-Unemploy/0427weekly.RData")
```


```{r}
summary(county_week_panel)
```





```{r Compile data- }
# Number of cover county number

# 1. cps_use 

need <- employ_county_week %>%
    mutate(payroll = 1) %>% 
    filter(!is.na(emp_combined)) %>% 
   select(countyfips, payroll) %>% distinct()
 
county_outcome_summary <- county_demo %>% left_join(need)

need <- cps_use %>% 
  mutate(cps = 1) %>% 
  select(COUNTY, cps) %>% 
  distinct() 
  

county_outcome_summary <- county_outcome_summary %>% left_join(need, c("countyfips" = "COUNTY"))


need <- ui_county %>% 
  mutate(ui = 1) %>% 
  select(countyfips, ui) %>% 
  distinct()

county_outcome_summary <- county_outcome_summary %>% left_join(need)

```
```{r statistics}

outcome_summary_use <- county_outcome_summary %>% 
  summarise(pop = n(),
            pay = sum(payroll == 1, na.rm = TRUE),
            cps = sum(cps == 1, na.rm = TRUE), 
            ui = sum(ui == 1, na.rm = TRUE)
            ) %>% gather(indicator, value, pop:ui) %>% 
  mutate(desc = "count")


d1 <- county_outcome_summary %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  gather(desc, value, totalhousehold:medianhouseholdincome ) %>% 
  mutate(indicator = "pop")


d2 <- county_outcome_summary %>% 
  filter(payroll == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  gather(desc, value, totalhousehold:medianhouseholdincome )%>% 
  mutate(indicator = "pay")

d3 <- county_outcome_summary %>% 
  filter(cps == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE )%>% 
  gather(desc, value, totalhousehold:medianhouseholdincome )%>% 
  mutate(indicator = "cps")

d4 <- county_outcome_summary %>% 
  filter(ui == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE )%>% 
  gather(desc, value, totalhousehold:medianhouseholdincome )%>% 
  mutate(indicator = "ui")

summary_outcome <- rbind(outcome_summary_use, d1, d2, d3, d4) 



summary_outcome$indicator <- factor(summary_outcome$indicator, level = c("cps","pay", "ui", "pop" ))

summary_outcome <- summary_outcome %>% 
                mutate(value_use = value, 
                       value_use = ifelse(desc %in% c("population", "totalhousehold") , value/1000, value),
                       facet = recode(desc, "count" = "Total Observations",
                                           "internetper" = "Internet Percentage", 
                                            "medianhouseholdincome" = "Median Household Income", 
                                            "population" = "Population/1000", 
                                            "totalhousehold" = "Total Household/1000") )
```

```{r}

summary_outcome %>%  ggplot(aes( y = indicator , x = value_use))+
                    geom_bar(width = 0.4, stat="identity") + 
                    scale_y_discrete(labels = c("pop" = "All Counties", "ui" = "Unemployment Insurance", "pay" = "Payroll", "cps" = "Current Population Survey"))+
              scale_alpha_manual(values = c(0.6,1)) +
              facet_wrap(~facet, scales = "free_x") + 
               theme_minimal()+  labs(x = "", y = "", title = "Data Representativeness" )

#scale_fill_manual(values = c("red","red","red","red")) +

```
```{r}

summary_outcome %>% filter(desc == "population")  %>% ggplot(aes( x = indicator , y = value ))+ geom_bar(stat="identity")

```

```{r}

```

