---
title: "s2-data-analysis"
author: "LetingZhang"
date: "5/1/2021"
output: html_document
---

# DESCRIPTION

```{r des}
# Descriptive analyses
# Sample & Correlation visualization
install.packages("gtsummary")
```

# LOAD LIBRARY

```{r Load library}
library(ggplot2)
library(socviz)
library(hrbrthemes)
library(ggrepel)
library(psych)
library(DataExplorer)
library(tidyverse)
library(bit64)
library(robustHD)
library(here)
library(haven)
library(kableExtra)
library(modelsummary)
library(flextable)
library(gtsummary)
library(labelled)
```


```{r Load data}
load("~/2. Covi_IT_Unemploy/0603weekly.RData")
```



# Create county-level statistics

```{r Create statistics on IT budget & industry distribution& IT service employee }
# Analyses on establishment in counties 

# - County population - basic & IT statistics

### = =  Median is not affected by winsorized or not. 


county_pop_basic <- ci_data_use  %>% select(SITEID, COUNTY, EMPLE, REVEN,
                          IT_BUDGET, HARDWARE_BUDGET, 
                       SOFTWARE_BUDGET,SERVICES_BUDGET) %>% 
  filter(!is.na(COUNTY) & IT_BUDGET != 0 & EMPLE!=0) %>%
  mutate_if(is.integer64, as.numeric) %>% 
  group_by(COUNTY) %>% 
  mutate(count_county_estab = n(), 
         it_budget_per_emp = IT_BUDGET/EMPLE,
         emple_win = ifelse(count_county_estab >1, winsorize(EMPLE), EMPLE), 
         reven_win = ifelse(count_county_estab >1, winsorize(REVEN), REVEN),  
         it_budget_win = ifelse(count_county_estab >1, winsorize(IT_BUDGET), IT_BUDGET) ,
         hard_budget_win = ifelse(count_county_estab >1, winsorize(HARDWARE_BUDGET), HARDWARE_BUDGET),
         software_budegt_win = ifelse(count_county_estab >1, winsorize(SOFTWARE_BUDGET), SOFTWARE_BUDGET),
         service_budget_win = ifelse(count_county_estab >1, winsorize(SERVICES_BUDGET), SERVICES_BUDGET)) %>% 
  summarise(count = n(), 
            across(EMPLE:it_budget_per_emp, mean, na.rm = TRUE, .names = "{col}_mean"), 
            across(emple_win:service_budget_win, mean, na.rm = TRUE, .names = "{col}_mean"),
            across(EMPLE:it_budget_per_emp, median, na.rm = TRUE, .names = "{col}_median")) %>% 
  ungroup()


county_pop_median <- county_pop_basic %>% 
                      select(!contains("mean")) %>% 
                      left_join(county_pop_industry) %>% 
                      left_join(county_qwi_agg %>% select(geography, its_emps_all), 
                                                      by = c( 'COUNTY' = 'geography'))

# - County population - Industry

county_pop_industry <- ci_data_use  %>% select(SITEID, COUNTY, IT_BUDGET, EMPLE, SICGRP ) %>% 
  filter(!is.na(COUNTY) & IT_BUDGET != 0 & EMPLE!=0) %>%
  group_by(COUNTY) %>% 
  mutate(count_total_est = n()) %>% 
  select(-c(IT_BUDGET, EMPLE)) %>% 
  group_by(COUNTY, SICGRP, count_total_est) %>% 
  summarise(count_sic = n()) %>% 
  ungroup() %>%
  mutate(per_sic = count_sic/count_total_est) %>% 
  select(-count_sic) %>% 
  spread(SICGRP,  per_sic)
  
  

# - County sample statistics  (sample used in analyses)

county_sample <-  county_week_panel %>% 
  select(countyfips, initclaims_rate_regular,  avg_new_death_rate, avg_new_case_rate, avg_median_home, IT_BUDGET_mean ) %>% 
  drop_na(c("countyfips", "initclaims_rate_regular",  "avg_new_death_rate", "avg_new_case_rate", "avg_median_home", "IT_BUDGET_mean")) %>% 
  select(countyfips) %>%
  distinct()


county_sample_basic <- county_sample %>% 
            left_join(county_pop_basic, by = c('countyfips' = 'COUNTY')) 

county_sample_industry <- county_sample %>% 
            left_join(county_pop_industry, by = c('countyfips' = 'COUNTY')) 

county_sample_stat <- county_sample_basic %>% left_join(county_sample_industry)



county_sample_median <- county_sample_basic %>% 
                            select(!contains("mean")) %>% 
                        left_join(county_sample_industry) %>% 
                        left_join(county_qwi_agg %>% select(geography, its_emps_all), 
                                                      by = c( 'countyfips' = 'geography')) 
                

# Add ACS data

county_acs <- read.csv(here("1.Data", "2.intermediate_data", "county_demo.csv"))

county_acs_new <- read.csv(here("1.Data", "2.intermediate_data", "county_demo.csv"))
 

county_sample_acs <- county_sample %>% 
                       select(-X)%>% 
              left_join(county_acs) 

county_sample_median <- county_sample_median %>% 
  left_join(county_acs %>% select(-X))

county_pop_median <- county_pop_median %>% 
  left_join(county_acs %>% rename("COUNTY" = "countyfips")%>%  select(-X))


```



# Sample vs Population CITIDB Descriptive Analysis

```{r Summary Statisitcs - IT budget & Industry, rows.print = 100}
library(psych)

df <- county_pop_basic %>% select(contains("median"))
psych::describe(df, fast = TRUE)[8:14,]


df <- county_sample_median_stat %>% select(contains("median"))
psych::describe(df, fast = TRUE)

#summary_table <- as.data.frame(psych::describe(df, fast = TRUE)) 
#summary_table %>% select(- c("vars", "n")) %>% kable(row.names = NULL)

# tmp <- do.call(data.frame, 
#            list(mean = apply(df, 2, function(x) mean(x, na.rm = T)),
#                 sd = apply(df, 2, sd),
#                 median = apply(df, 2, median),
#                 min = apply(df, 2, min),
#                 max = apply(df, 2, max),
#                 n = apply(df, 2, length)))


```



```{r DEMO Sample vs not in sample - comparison }

#install.packages("rstatix")

mydata <- iris %>%
  filter(Species != "setosa") %>%
  as_tibble()

mydata %>% sample_n(6)
mydata.long <- mydata %>%
  pivot_longer(-Species, names_to = "variables", values_to = "value")

stat.test <- mydata.long %>%
  group_by(variables) %>%
  t_test(value ~ Species) %>%
  add_significance()

library(rstatix)
library(ggpubr)

sample_pop_long <-  sample_pop_diff%>% 
  pivot_longer(-c(COUNTY, not_in_sample), names_to = "variable", values_to = "value" )

t.test <- sample_pop_long  %>% 
  select(-COUNTY) %>% 
  group_by(variable) %>% 
  t_test(value ~ not_in_sample) %>% 
  adjust_pvalue(method = "BH") %>% 
  add_significance()

write.csv(t.test, here("3.Report", "samplepopttest.csv")) # use this stat in table 
```

```{r}
var_label(sample_pop_diff ) <- list(count = "No. Establishment",
                                    EMPLE_median = "No. Employees",
                                    REVEN_median = "Revenue",
                                    IT_BUDGET_median = "IT Budget",
                                    HARDWARE_BUDGET_median = "Hardware Budget",
                                    SOFTWARE_BUDGET_median = "Software Budget",
                                    SERVICES_BUDGET_median = "Service Budget",
                                    `AG-M-C` = "Agriculture",
                                    EDUC = "Education",
                                    `F-I-RE` = "Finance/Insurance",
                                    GOVT = "Government",
                                    MANUF = "Manufacturing",
                                    MED = "Medicare",
                                    SVCS = "Services",
                                    `TR-UTL` = "Transportation/Utilities",
                                    `WHL-RT` = "Wholesale/Retailers",
                                    its_emps_all = "IT Service Employees")
    


tbl <- sample_pop_diff %>% 
  select(-c(COUNTY, count_county_estab_median, 
            it_budget_per_emp_median, count_total_est, 
            `NON-CL`, totalhousehold, population,
            internetper, medianhouseholdincome,
            meanincome, county_appear_time )) %>% 
  tbl_summary(by = not_in_sample,
     statistic = list(all_continuous() ~ "{mean} ({sd})"),
     type = list(REVEN_median ~ "continuous"),
                  digits = all_continuous() ~ 2,
     missing = "no") %>% 
  add_p( test = everything() ~ "t.test") 

tbl


tbl %>%
  as_gt() %>%
  gt::gtsave( filename = here("3.Report", "appendix_sample_pop.rtf"))
  # as_flex_table() %>%
  # save_as_docx(path =here("3.Report", "appendix_sample_pop.docx"))
```


```{r}

sample_pop_long  %>%
  filter(variable %in% c("count", "EMPLE_median", "IT_BUDGET_median", "SOFTWARE_BUDGET_median", "SERVICES_BUDGET_median", "its_emps_all ", "REVEN_median") ) %>% 
  ggplot(aes(x = value , fill = factor(not_in_sample)) ) +
    geom_density(alpha=0.3) + scale_x_log10() + facet_wrap(~variable, scales = "free") + theme_bw()


sample_pop_long  %>%
  filter(variable %in% c("AG-M-C", "EDUC", "F-I-RE", "GOVT", "MANUF", "MED", "SVCS", "TR-UTL", "WHL-RT") ) %>% 
  ggplot(aes(x = value , fill = factor(not_in_sample)) ) +
    geom_density(alpha=0.3) + scale_x_log10() + facet_wrap(~variable, scales = "free") +  theme_bw()


sample_pop_long  %>%
  filter(variable %in% c("population", "internetper","totalhousehold",  "medianhouseholdincome") ) %>% 
  ggplot(aes(x = value , fill = factor(not_in_sample)) ) +
    geom_density(alpha=0.3) + scale_x_log10() + facet_wrap(~variable, scales = "free") +  theme_bw()
```



```{r}
ttest <- sample_pop_diff %>% 
  pivot_longer(-c(COUNTY,sample), names_to = "var", values_to = "value") %>% 
  arrange(COUNTY, sample)
  
```


```{r}
library(Hmisc)
describe(county_sample_basic) %>% html()
```



# Comparison between three data sources

```{r Compile data- }
# Number of cover county number

# 1. cps_use 

need <- employ_county_week %>%  # Chetty employment data
    mutate(payroll = 1) %>% 
    filter(!is.na(emp_combined)) %>% 
   select(countyfips, payroll) %>% distinct()
 
county_outcome_summary <- county_demo %>% left_join(need) # County population - merge with Chetty employment data

need <- cps_use %>% 
  mutate(cps = 1) %>% 
  select(COUNTY, cps) %>% 
  distinct() 
  

county_outcome_summary <- county_outcome_summary %>% left_join(need, c("countyfips" = "COUNTY"))


need <- ui_county %>% 
  mutate(ui = 1) %>% 
  select(countyfips, ui) %>% 
  distinct()

county_outcome_summary <- county_outcome_summary %>% left_join(need)

```

```{r Statistics}

outcome_summary_use <- county_outcome_summary %>% 
  summarise(pop = n(),
            pay = sum(payroll == 1, na.rm = TRUE),
            cps = sum(cps == 1, na.rm = TRUE), 
            ui = sum(ui == 1, na.rm = TRUE)
            ) %>% gather(indicator, value, pop:ui) %>% 
  mutate(desc = "count")


d1 <- county_outcome_summary %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  gather(desc, value, totalhousehold:medianhouseholdincome) %>% 
  mutate(indicator = "pop")


d2 <- county_outcome_summary %>% 
  filter(payroll == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  gather(desc, value, totalhousehold:medianhouseholdincome )%>% 
  mutate(indicator = "pay")

d3 <- county_outcome_summary %>% 
  filter(cps == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE )%>% 
  gather(desc, value, totalhousehold:medianhouseholdincome )%>% 
  mutate(indicator = "cps")

d4 <- county_outcome_summary %>% 
  filter(ui == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE )%>% 
  gather(desc, value, totalhousehold:medianhouseholdincome )%>% 
  mutate(indicator = "ui")

summary_outcome <- rbind(outcome_summary_use, d1, d2, d3, d4) 



summary_outcome$indicator <- factor(summary_outcome$indicator, level = c("cps","pay", "ui", "pop" ))

summary_outcome <- summary_outcome %>% 
                mutate(value_use = value, 
                       value_use = ifelse(desc %in% c("population", "totalhousehold") , value/1000, value),
                       facet = recode(desc, "count" = "Total Observations",
                                           "internetper" = "Internet Percentage", 
                                            "medianhouseholdincome" = "Median Household Income", 
                                            "population" = "Population/1000", 
                                            "totalhousehold" = "Total Household/1000") )
```

```{r}

summary_outcome %>%  ggplot(aes( y = indicator , x = value_use))+
                    geom_bar(width = 0.4, stat="identity") + 
                    scale_y_discrete(labels = c("pop" = "All Counties", "ui" = "Unemployment Insurance", "pay" = "Payroll", "cps" = "Current Population Survey"))+
              scale_alpha_manual(values = c(0.6,1)) +
              facet_wrap(~facet, scales = "free_x") + 
               theme_minimal()+  labs(x = "", y = "", title = "Data Representativeness" )

#scale_fill_manual(values = c("red","red","red","red")) +

```
```{r}

summary_outcome %>% filter(desc == "population")  %>% ggplot(aes( x = indicator , y = value ))+ geom_bar(stat="identity")

```

# IT Budget Comparsion

```{r}

site2019 <- fread(here("1.Data", "1.raw_data", "USA_2019", "SiteDescription.TXT"), select = col)

col <- c("SITEID", "PRIMARY_DUNS_NUMBER", "COMPANY", "STATE", "COUNTY" ,"ZIPCODE", "EMPLE", "REVEN", "SIC2_CODE", "SIC2_DESC")

site2020 <- fread(here("1.Data", "1.raw_data", "citdb20", "SiteDescription.TXT"), select = col)

it_spend2020<- fread(here("1.Data", "1.raw_data", "citdb20", "ITSpend.TXT"))

site_it2020 <- merge(site2020, it_spend2020 )

rm(site2020, it_spend2020)

```




# Synthetic Control

```{r}
install.packages('gsynth', type = 'source')
library(gsynth)

```

```{r}

data(gsynth)
ls()

```

```{r}
head(simdata)
```

```{r}
library(panelView)
```

```{r}
panelView(Y ~ D, data = simdata,  index = c("id","time"), pre.post = TRUE) 
```

```{r}
panelView(Y ~ D, data = simdata,  index = c("id","time"), type = "outcome") 
```

```{r}
system.time(
    out <- gsynth(Y ~ D + X1 + X2, data = simdata, index = c("id","time"), force = "two-way", CV = TRUE, r = c(0, 5), se = TRUE, inference = "parametric", nboots = 1000, parallel = FALSE)
)
```

```{r}
print(out)
out$est.att
out$est.avg
out$est.beta
```
```{r}
plot(out)
```
```{r}
plot(out, theme.bw = FALSE) 
```

```{r}
plot(out, type = "gap", ylim = c(-3,12), xlab = "Period", main = "My GSynth Plot")
```
```{r}
plot(out, type = "raw")
```
```{r}
plot(out,type = "raw", legendOff = TRUE, ylim=c(-10,40), main="")
```

```{r}
plot(out, type = "counterfactual", raw = "none", main="")
```
```{r}
plot(out, type = "ct", raw = "none", main = "", shade.post = FALSE)
```
```{r}
plot(out, type = "counterfactual", raw = "band", xlab = "Time", ylim = c(-5,35))
```

```{r}
plot(out, type = "counterfactual", raw = "all")
```

```{r}
plot(out, type = "loadings")
```

```{r }
library(readstata13)
library(here)
panel_use <-read.dta13(here("Stata", "county_week_panel_1201.dta"))
panel_use$treatment <- panel_use$tre * panel_use$q4_high_it_budget_median

demo <- panel_use %>% filter(!is.na(initclaims_rate_regular) & !is.na(avg_home_prop) & !is.na( avg_new_death_rate) &!is.na(avg_new_case_rate))

demo1 <- demo %>% select(county, week, treatment, initclaims_rate_regular) %>% head(1000)

```



```{r}
panelView(initclaims_rate_regular ~ treatment, data = demo1,  index = c("county", "week"), pre.post = TRUE, by.timing = TRUE)
```




```{r}
out <- gsynth(initclaims_rate_regular ~  treatment + avg_home_prop +  avg_new_death_rate + avg_new_case_rate, data = demo,  index = c("county", "week"), se = TRUE, inference = "nonparametric", r = c(0, 4), CV = TRUE, force = "two-way", min.T0 = 6,  seed = 02139)


```

```{r}
out <- gsynth(initclaims_rate_regular ~  treatment + avg_home_prop +  avg_new_death_rate + avg_new_case_rate, data = demo,  index = c("county", "week"), se = TRUE, inference = "nonparametric", r = c(0, 4), CV = TRUE, force = "two-way", min.T0 = 7,  seed = 30000)
```

```{r}
plot(out)
```

```{r}
plot(out, type = "counterfactual", raw = "none", main="")
```

```{r}
plot(out, type = "ct", raw = "none", main = "", shade.post = FALSE)
```


```{r}

plot(out, type = "counterfactual", raw = "band", xlab = "Time", ylim = c(0,4))

```



```{r}
plot(out, type = "counterfactual", raw = "all")
```

