---
title: "Plots"
author: "Leting Zhang"
date: "8/28/2021"
date: "11/28/2021"
output: html_document
---

```{r Load library}

library(tidyverse)
library(here)
library(data.table)
library(haven)
library(maps)
library(ggplot2)
library(robustHD)
```

# Config
```{r Path}
raw_data <- here("1.Data", "1.raw_data")
output <- here("1.Data", "3.output_data")
```


# Import the panel data
```{r import data}
# data

#county_week <- read_dta(here("Stata", "county_week_panel_aug_analysis.dta"))
county_week <- read_dta(here("Stata", "county_week_panel_dec_process.dta"))

county_week <- as.data.frame(county_week)

```


```{r differentiate sample vs population}

mainvar <- c("county", "week", "month", "state", "initclaims_rate_regular",
             "avg_new_case_count", "avg_new_death_rate", "avg_home_prop", "it_median", 
             "its_emps_all")

county_week_use <- county_week %>% 
  select(mainvar) %>% 
  filter(!is.na(initclaims_rate_regular) & !is.na(it_median)) 

```

# Plots - Unemployment rate & Stay-at-home

```{r Unemployment rate }
#saveRDS(ui_state_policy, here(output, "us_state_policy.rds" ))

ui_state_policy <- readRDS("~/2.Covid_IT_Employment/1.Data/3.output_data/us_state_policy.rds")
 
# ui_state_policy

ggplot(data = ui_state_policy ,
            mapping = aes(x = month, y = initclaims_rate_regular,
                          group = state, color = factor(stayathome)) ) +
      geom_line() +
      geom_smooth(mapping = aes(group = stayathome), size= 1.5, se = TRUE) +
      coord_cartesian(c(min(ui_state_policy$month), max(ui_state_policy$month))) +  scale_x_continuous(breaks = seq(1,10,1), labels = function(x)month.abb[x])+
   scale_color_manual(name = "Stay at Home Order Enforcement", labels = c("No", "YES"),values=c( "#264653", "#e76f51"))+
      labs(x = "", y = " % Rate", title = "State Unemployment Insurance (UI) Claim Rate - 2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Note: UI claim rates =  Number of initial claims per 100 people in the 2019 labor force.")
```


# Plots - Compare three unemployementa data sources

```{r Compile data- Comparison between three data sources}
# Basic idea:  Extract covered county number
county_week <- read_dta(here("Stata", "county_week_panel_ui_emp.dta")) # UI, Employment data
load("~/2.Covid_IT_Employment/CPS_2021.RData") # CPS data 


# Benchmark: All county 
mavar <-  c("county", "internetper", "medianhouseholdincome", "population", "totalhousehold")

county_char <-  county_week %>% 
  select(all_of(mavar)) %>% distinct()


# Unemployment insurance claim  - county

ui_county <- county_week %>% 
    select(county,initclaims_rate_regular ) %>% 
    filter(!is.na(initclaims_rate_regular)) %>% 
    mutate(ui = 1) %>% 
   select(county, ui) %>% distinct()

# Employment data - county

employ_county <- county_week %>% 
    select(county,emp_combined ) %>% 
    filter(!is.na(emp_combined)) %>% 
    mutate(payroll = 1) %>% 
    select(county, payroll) %>% distinct()

# CPS data  - county

cps_county <- cps_data %>% 
    filter(COUNTY!= 0 & YEAR == 2020) %>% 
    select(COUNTY) %>%
    distinct() %>% 
    mutate(cps = 1)

colnames(cps_county)[1] <- "county"


# Combine all data

county_datasource_all <- county_char %>% 
    left_join(employ_county) %>% 
    left_join(ui_county) %>% 
    left_join(cps_county)


```


```{r Calculate the average}

data_obs_count <- county_datasource_all %>% 
  summarise(pop = n(),
            pay = sum(payroll == 1, na.rm = TRUE),
            cps = sum(cps == 1, na.rm = TRUE), 
            ui = sum(ui == 1, na.rm = TRUE)
            ) %>% gather(indicator, value, pop:ui) %>% 
  mutate(describe = "count") 


data_char_avg <- county_datasource_all %>% 
  summarise_at(c(2:5), mean, na.rm = TRUE ) %>% 
   mutate(indicator = "pop") %>% 
  add_row( # add payroll county 
    county_datasource_all %>% 
  filter(payroll == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  mutate(indicator = "pay")
  ) %>% 
  add_row( # add ui county 
     county_datasource_all %>% 
  filter(ui == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  mutate(indicator = "ui")
  ) %>% 
  add_row( # add cps county 
      county_datasource_all %>% 
  filter(cps == 1) %>% 
  summarise_at(2:5, mean, na.rm = TRUE ) %>% 
  mutate(indicator = "cps")
  ) %>% 
  gather(describe, value, 1:4, -indicator)



data_summary <-  data_obs_count %>% 
           add_row(data_char_avg)


data_summary <- data_summary %>% 
                mutate(value_use = value, 
                       value_use = ifelse(describe %in% c("population", "totalhousehold") , value/1000, value),
                       facet = recode(describe, "count" = "Total Observations",
                                      "internetper" = "Internet Percentage", 
                                      "medianhouseholdincome" = "Median Household Income", 
                                      "population" = "Population/1000", 
                                      "totalhousehold" = "Total Household/1000") )

data_summary$indicator <- factor(data_summary$indicator, level = c("cps", "pay", "ui", "pop" ))
data_summary <- data_summary %>% 
  mutate(benchmark = ifelse(indicator == "pop", "Benchmark", "Other Data Sources"))
```

```{r Plot}

data_summary1 <- data_summary %>% 
  mutate(benchmark = ifelse(indicator == "pop", "Benchmark", "Unemployment Data Sources"))

data_summary1 %>%  ggplot( aes(y = indicator , x = value_use)) +
                  geom_bar(aes(fill = benchmark), width = 0.4, 
                                   stat="identity",  color = "black")  +
                  scale_y_discrete(labels = c("pop" = "All Counties",
                                              "ui" = "Unemployment Insurance", 
                                              "pay" = "Payroll", 
                                              "cps" = "Current Population Survey"))+
                  scale_fill_manual(values = c("white", "grey"))+
                  scale_alpha_manual(values = c(0.6,1)) +
                  facet_wrap(~facet, scales = "free_x") + 
                  theme_minimal()+  
                  labs(x = "", y = "", title = "Unemployement Data Sources: County-level Characteristics" ) +
                  theme(legend.position = "top", 
                        axis.title.y = element_blank(),
                        plot.title = element_text(size = rel(1.3), hjust = 0.3)) +
                  guides(fill =guide_legend(title=""))


```




# Plots - Unemployement rate - 2019 longer trend
## update 2023 April

```{r}

library(zoo)
# Read data: Unemployment rate 2019 2020
county_unemprate_19_20 <- readRDS("~/2.Covid_IT_Employment/1.Data/3.output_data/county_unemprate_19_20.rds")

# Process county name
county_unemprate_19_20 <- county_unemprate_19_20 %>% 
                          mutate(county_name = str_replace(county," County", ""), # Remove "County"
                                 county_name = substr(county_name, 1, nchar(county_name) - 3), #"Remove (U)"
                                 county_name = trimws(county_name)) %>%  #Remove leading/trailing white spaces
                          select(-c(series_id, county))


# Read data: county IT budget
county_week <- as.data.frame(read_dta(here(output, "county_week_panel_april_2023.dta"))) 

county_it <- county_week %>% select(county, month, initclaims_rate_regular, new_q4_high_it,skillq4_county_exc, skillq4_county, skillq2_county) %>% distinct()%>%mutate(countyfips = as.integer(county))

county_info <- read.csv(here(raw_data, "GeoIDs - County.csv"))
county_info <- county_info %>% 
  mutate(county_name = paste(countyname, ",", " ", stateabbrev, sep = "")) %>% 
  select(countyfips, county_name)

county_use <- county_it
#%>% 
#  left_join(county_info) %>% 
 # left_join(county_unemprate_19_20) %>% 
# filter(period != "M13") %>% 
  #mutate(month = as.numeric(substr(period, 2, 3)),
     #    date = as.yearmon(paste(year,month, sep = "-")) )



county_it <- county_week %>% select(county, month, initclaims_rate_regular, new_q4_high_it,skillq4_county_exc, skillq4_county, skillq2_county) %>% distinct()%>%mutate(countyfips = as.integer(county))







```


```{r}
county_it_new <- county_week %>% select(county, new_q4_high_it,skillq4_county_exc, skillq4_county, skillq2_county) %>% distinct()%>%mutate(countyfips = as.integer(county))

county_info <- read.csv(here(raw_data, "GeoIDs - County.csv"))
county_info <- county_info %>% 
  mutate(county_name = paste(countyname, ",", " ", stateabbrev, sep = "")) %>% 
  select(countyfips, county_name)

county_use_new <- county_it_new%>%
 left_join(county_info) %>%
left_join(county_unemprate_19_20) %>%
filter(period != "M13") %>%
mutate(month = as.numeric(substr(period, 2, 3)),
   date = as.yearmon(paste(year,month, sep = "-")),
   value = as.numeric(value))
  




skill_group_county_unemployrate_new <- county_use_new %>%
  group_by( new_q4_high_it, skillq4_county_exc,date) %>%
  mutate(unemp_q4_exc = mean(value, na.rm = TRUE)) %>%
  group_by(new_q4_high_it, skillq4_county,date) %>%
  mutate(unemp_q4 = mean(value, na.rm = TRUE)) %>%
  group_by(new_q4_high_it, skillq2_county,date) %>%
   mutate(unemp_q2 = mean(value, na.rm = TRUE)) %>%
  ungroup()  %>%
  select( date, new_q4_high_it, skillq4_county_exc, skillq4_county, skillq2_county,
         unemp_q4_exc, unemp_q4, unemp_q2 ) %>%
  distinct()
```



```{r County-level -Unemployment rates for counties of different skill-level}
skill_group_county_unemployrate_new %>% filter(!is.na(skillq4_county_exc) & new_q4_high_it == 1 &  skillq4_county_exc!='') %>%
  ggplot(aes(x = date, y = unemp_q4_exc, 
            color = factor( skillq4_county_exc))) +
  geom_line(size= 1.2) +
  scale_color_manual(values=c( "blue", "red","grey"))+
  labs(x = "", y = " % Rate", title = "County Unemployment Rate: 2019 - 2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
  
```



```{r}
skill_group_county_unemployrate_new %>% filter(!is.na(skillq4_county) & new_q4_high_it == 1 &  skillq4_county!='') %>%
  ggplot(aes(x = date, y = unemp_q4, 
            color = factor( skillq4_county))) +
  geom_line(size= 1.2) +
  scale_color_manual(values=c( "blue", "red","grey"))+
  labs(x = "", y = " % Rate", title = "County Unemployment Rate: 2019 - 2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
  
```

```{r}
skill_group_county_unemployrate_new %>% filter(!is.na(skillq2_county) & new_q4_high_it == 1 &  skillq2_county!='') %>%
  ggplot(aes(x = date, y = unemp_q2, 
            color = factor( skillq2_county))) +
  geom_line(size= 1.2) +
  scale_color_manual(values=c( "blue", "red","grey"))+
  labs(x = "", y = " % Rate", title = "County Unemployment Rate: 2019 - 2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
  
```



```{r Summarize and calculate the mean value}
it_group_county_unemployrate <- county_use %>% 
  mutate(value = as.numeric(value)) %>% 
  group_by(q4_high_it_budget_median, date) %>% 
  summarise(unemployment = median(value, na.rm = TRUE)) %>% 
  ungroup() 
  

skill_group_county_unemployrate <- county_use %>%
  group_by( new_q4_high_it, skillq4_county_exc, month) %>%
  mutate(unemp_q4_exc = mean(initclaims_rate_regular, na.rm = TRUE)) %>%
  group_by(new_q4_high_it, skillq4_county, month) %>%
  mutate(unemp_q4 = mean(initclaims_rate_regular, na.rm = TRUE)) %>%
  group_by(new_q4_high_it, skillq2_county, month) %>%
   mutate(unemp_q2 = mean(initclaims_rate_regular, na.rm = TRUE)) %>%
  ungroup()  %>%
  select( month, new_q4_high_it, skillq4_county_exc, skillq4_county, skillq2_county,
         unemp_q4_exc, unemp_q4, unemp_q2 ) %>%
  distinct()



skill_group_DEMO <- county_use %>%
  group_by( new_q4_high_it, skillq4_county_exc, month) %>%
  summarise(unemp_q4_exc = mean(initclaims_rate_regular, na.rm = TRUE))




skill_group_DEMO %>% filter(!is.na(skillq4_county_exc) & !is.na(new_q4_high_it) &  skillq4_county_exc!='') %>%
  ggplot(aes(x = month, y = unemp_q4_exc, 
            color = (factor( skillq4_county_exc)))) +
  geom_line(aes(linetype =  factor(new_q4_high_it)), size= 1.2) + 
  scale_x_continuous(breaks = seq(1,10,1), 
                                labels = function(x)month.abb[x]) +
scale_linetype_manual(values = c("dotdash", "solid"), labels = c("Low", "High"))+
  scale_color_manual(values=c( "blue", "red","grey"))+
  guides(color = guide_legend(title = "Skill-level"),
        linetype = guide_legend(title = "BAIT")) +
  labs(x = "", y = " % Rate", title = "County Unemployment Rate:2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")

```


```{r}
table(skill_group_county_unemployrate$skillq4_county_exc)
table(skill_group_county_unemployrate$skillq4_county)
table(skill_group_county_unemployrate$skillq2_county)
```


```{r}


skill_group_county_unemployrate %>% filter(!is.na(skillq4_county_exc) & !is.na(new_q4_high_it) &  skillq4_county_exc!='') %>%
  ggplot(aes(x = month, y = unemp_q4_exc, 
            color = (factor( skillq4_county_exc)))) +
  geom_line(aes(linetype =  factor(new_q4_high_it)), size= 1.2) + 
  scale_x_continuous(breaks = seq(1,10,1), 
                                labels = function(x)month.abb[x]) +
scale_linetype_manual(values = c("dotdash", "solid"), labels = c("Low", "High"))+
  scale_color_manual(values=c( "blue", "red","grey"))+
  guides(color = guide_legend(title = "Skill-level"),
        linetype = guide_legend(title = "BAIT")) +
  labs(x = "", y = " % Rate", title = "County Unemployment Rate:2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
  
```

```{r}
skill_group_county_unemployrate %>% filter(!is.na(skillq4_county) & !is.na(new_q4_high_it) &  skillq4_county!='') %>%
  ggplot(aes(x = month, y = unemp_q4, 
            color = (factor( skillq4_county)))) +
  geom_line(aes(linetype =  factor(new_q4_high_it)), size= 1.2) +
  scale_x_continuous(breaks = seq(1,10,1), 
                                labels = function(x)month.abb[x]) + 
scale_linetype_manual(values = c("dotdash", "solid"), labels = c("Low", "High"))+
  scale_color_manual(values=c( "blue", "red","grey"))+
  guides(color = guide_legend(title = "Skill-level"),
        linetype = guide_legend(title = "BAIT")) +
  labs(x = "", y = " % Rate", title = "County Unemployment Rate:2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
```

```{r}
skill_group_county_unemployrate %>% filter(!is.na(skillq2_county) & !is.na(new_q4_high_it) &  skillq2_county!='') %>%
  ggplot(aes(x = month, y = unemp_q2, 
            color = (factor( skillq2_county)))) +
  geom_line(aes(linetype =  factor(new_q4_high_it)), size= 1.2) +
  scale_x_continuous(breaks = seq(1,10,1), 
                                labels = function(x)month.abb[x]) + 
scale_linetype_manual(values = c("dotdash", "solid"), labels = c("Low", "High"))+
  scale_color_manual(values=c( "blue", "red","grey"))+
  guides(color = guide_legend(title = "Skill-level"),
        linetype = guide_legend(title = "BAIT")) +
  labs(x = "", y = " % Rate", title = "County Unemployment Rate:2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
```


```{r Plot Unemployment rates based on county BAIT}

it_group_county_unemployrate %>% 
  
  ggplot(aes(x = date, y = unemployment, 
            color = factor(new_q4_high_it) )) +
  geom_line(size= 1.2) +
  scale_color_manual(name = "High BAIT", labels = c("YES", "NO"),values=c( "blue", "red"))+
  labs(x = "", y = " % Rate", title = "County Unemployment Rate: 2019 - 2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
  

```


```{r}
county_week_use <- county_week %>% select(county, week, initclaims_rate_regular, new_q4_high_it) %>% filter(!is.na(new_q4_high_it) ) %>% distinct()%>%
group_by(week, new_q4_high_it) %>% 
summarise(unemployment = mean(initclaims_rate_regular, na.rm = TRUE))




county_week_use %>% 
  
  ggplot(aes(x = week, y = unemployment, 
            color = factor(new_q4_high_it) )) +
  geom_line(size= 1.2) +
  scale_color_manual(name = "High BAIT", labels = c("YES", "NO"),values=c( "blue", "red"))+
  labs(x = "", y = " % Rate", title = "County Weekly Unemployment Rate: 2019 - 2020") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")

```


#Plots - BAIT distribution map 

```{r}
ci_summarise_all <- readRDS("~/2.Covid_IT_Employment/1.Data/1.raw_data/ci_summarise_all.rds")
county_map <- readRDS("~/2.Covid_IT_Employment/1.Data/1.raw_data/county_map.rds")


mid_data <- ci_summarise_all %>% select(COUNTY,IT_BUDGET_median) %>%
  mutate(it = log(IT_BUDGET_median + 1),
         it2= winsorize(it))

mid_data %>%
  right_join(county_map, by = c("COUNTY"  = "county") ) %>% 
  ggplot(mapping = aes(x = long, y = lat, 
                       fill = it2, group = group)) +
      geom_polygon(color = "gray90", size = 0.05) +
      coord_equal() + 
    scale_fill_gradient2(high = "blue", mid = "white", low= "red", 
                        limits=c(10.37,10.93),
                         breaks = c(10.37, 10.65, 10.92), 
                         midpoint = 10.65,
                         labels = paste("$", c('32,208', '42,192', '54,176')),
                         guide = "colorbar") +
      labs(fill = "") + ggthemes::theme_map() + theme(legend.position = "right")+  
  labs(x = "", y = "", title = " 2019 County-level Business Access to IT (BAIT) - Map",
        caption = "Note: The measurement is county-level median of IT budget per establishment (USD)") +  
      theme(plot.title = element_text(size = rel(1.5), hjust = 0.5),
           plot.caption = element_text(size = rel(1.2), hjust = 0),
           #legend.title = element_text(size = rel(1.5)),
            legend.text = element_text(size=8),
           legend.position = c(0.92, 0.40)) 

```




# Plots - County-level IT investment density

```{r IT investment -4th quantile}

# Density with segments (4th quantile)

 county_it_unique<- county_week_use %>% 
  select(county, it_median) %>% 
  distinct()


 q4 <-  quantile(county_it_unique$it_median)[4]


county_week_use %>% 
  select(county, it_median) %>% 
  distinct() %>% 
  ggplot(aes(x = it_median)) +
  geom_density() + 
  geom_vline(xintercept = q4, linetype="dashed", color = "blue") +
  annotate('text', x = q4+25000, y = 0.00007, label = "> High BAIT", color = "blue", size = 5)+
 #  geom_vline(xintercept = 46603, linetype="dashed", color = "orange") +
  #annotate('text', x = 46603+50000, y = 0.00005, label = "Orange County: 46603 USD", color = "orange", size = 5)+
  labs(x = "County-level median of IT Budget per Establishment (USD)", y = " Density", title = "2019 County-level Business Acess to IT (BAIT) - Density") +  
      theme_bw()
  


```

# Plots - Unemployment rate group by high/low BAIT


```{r}

plot <- county_week %>% 
  select(month, county, stayweek, tre, initclaims_rate_regular,q4_high_it) %>% 
  filter( !is.na(stayweek)) %>% 
  group_by(month, q4_high_it) %>% 
  summarise(avg_initclaims_rate = mean(initclaims_rate_regular, na.rm = TRUE))


plot %>%
  ggplot(aes(x = month, y = avg_initclaims_rate,
             color =  factor(q4_high_it_budget_median)) ) +  
              geom_line(size = 1.3) + 
             scale_x_continuous(breaks = seq(1,10,1), 
                                labels = function(x)month.abb[x])+
             labs(x = "", y = "Rate %", 
       title = "2020 The Impact of BAIT on Unemployment Rate \n After Stay-at-home Enforcement  ")+
  scale_color_manual(name = "Business Access to IT (BAIT)", 
                     labels = c("Low", "High"),values=c( "red", "blue")) +
  theme_minimal() + 
  theme(plot.title = element_text(size = rel(1.2), hjust = 0.5, ),
        legend.title = element_text(size = rel(1)),
        legend.key.width= unit(1, 'cm'),
        legend.text = element_text(size=10, color = "#696969"),
        axis.text=element_text(size= 11),
        axis.title.y = element_text(size = rel(1.2), angle = 90),
        axis.title.x = element_text(size = rel(1.2)),
        plot.caption = element_text(size = rel(1), hjust = 0),
        legend.position = "top") +
  labs(caption = "Note: Unemployment rate =  Number of initial unemployment insurance (UI) claims per 100 people in the 2019 labor force.") +
  geom_vline(xintercept = 3,
             color =  "#191970", size=1.2, linetype="dashed") + 
  annotate("text", x = 1.8, y = 2.8, label = "Before", size = 4)+
  annotate("text", x = 6, y = 2.8, label = "After", size = 4) +
  annotate("text", x = 1.8, y = 1.5, label = "Stay-at-home \n enforcement", size = 4) +
  annotate("segment", x = 1, xend = 2.8, y = 3, yend = 3,
           arrow = arrow(ends = "both", angle = 90, length = unit(0.5,"cm")), size = 1) + 
  annotate("segment", x = 3.2, xend = 11, y = 3, yend = 3,
           arrow = arrow(ends = "both", angle = 90, length = unit(0.5,"cm")), size = 1) + 
  annotate("segment", x = 2, xend = 2.8, y = 1.8, yend =2.3 ,
           colour = "black", size = 1, arrow = arrow())

```

# Update 2024 April
```{r Plots }


county_new_week_pane_use


county_new_plot_week_use <- county_new_week_panel_use %>% select(countyfips, week_use, initclaims_rate_regular)  %>% distinct()%>%
group_by(week_use) %>% 
summarise(unemployment = mean(initclaims_rate_regular, na.rm = TRUE))




county_new_plot_week_use %>% 
  
  ggplot(aes(x = week_use, y = unemployment)) +
  geom_line(size= 1.2) +
  labs(x = "", y = " % Rate", title = "County Weekly Unemployment Rate: 2020 - 2021") +  
      theme_minimal() + 
      theme(plot.title = element_text(size = rel(1.6), hjust = 0.5),
           legend.title = element_text(size = rel(0.8)),
           plot.caption = element_text(size = rel(1)),
           legend.position = "top") +
    labs(caption = "Data Source: U.S. Bureau of Labor Statistics - Local Area Unemployment Statistics (LAUS)")
```

